import { MenuItem } from '../models/menu.model';

// menu items for vertcal and detached layout
const MENU_ITEMS: MenuItem[] = [
    { key: 'navigation', label: '', isTitle: true },
    {
        key: 'dashboards',
        label: 'Dashboard',
        isTitle: false,
        icon: 'activity',
        link: '/dashboard-1',  // Direct link to Dashboard 1
    },
    {
        key: 'forms',
        label: 'Patient Registration',
        isTitle: false,
        icon: 'user-plus',
        link: '/forms/basic'
        
    },
    {
        key: 'apps-calendar',
        label: 'Treatment Plan',
        isTitle: false,
        icon: 'clipboard',
        link: '/forms/treatment-plan',
    },
    {
        key: 'apps-chat',
        label: 'Histopathology',
        isTitle: false,
        icon: 'thermometer', // Changed from 'microscope'
        link: '/forms/histopathology',
    },
    {
        key: 'apps-ecommerce',
        label: 'Upload Documents',
        isTitle: false,
        icon: 'upload',
        link: '/forms/upload-documents',
    },
    {
        key: 'apps-crm',
        label: 'Followup',
        isTitle: false,
        icon: 'refresh-cw',
        link: '/forms/followup',  // Changed from 'repeat'
    },
    {
        key: 'apps-email',
        label: 'Discharge Notes',
        isTitle: false,
        icon: 'file-text',
        link: '/forms/discharge-notes',
    },
   
    { 
        key: 'apps-companies',
        label: 'OT List + Census', 
        isTitle: false, icon: 'list', 
        link: '/forms/ot-list-census' },   
    {
        key: 'apps-tasks',
        label: 'Fundus',
        isTitle: false,
        icon: 'eye',
        link: '/forms/fundus',
    }
    // Removed Contacts, Tickets, and File Manager
];


// menu items for two column menu layout 
const TWO_COl_MENU_ITEMS: MenuItem[] = [
    {
        key: 'dashboard',
        icon: 'home',
        label: 'Dashboard',
        isTitle: true,
        link: '/dashboard-1',  // Direct link to Dashboard 1
    },
    {
        key: 'apps',
        icon: 'grid',
        label: 'Apps',
        isTitle: true,
        children: [
            {
                key: 'apps-calendar',
                label: 'Calendar',
                isTitle: false,
                icon: 'calendar',
                link: '/apps/calendar',
                parentKey: 'apps',
            },
            {
                key: 'apps-chat',
                label: 'Chat',
                isTitle: false,
                icon: 'message-square',
                link: '/apps/chat',
                parentKey: 'apps',
            },
            {
                key: 'apps-ecommerce',
                label: 'Ecommerce',
                isTitle: false,
                icon: 'shopping-cart',
                parentKey: 'apps',
                collapsed: true,
                children: [
                    {
                        key: 'ecommerce-dashboard',
                        label: 'Dashboard',
                        link: '/apps/ecommerce/dashboard',
                        parentKey: 'apps-ecommerce',
                    },
                    {
                        key: 'ecommerce-products',
                        label: 'Products',
                        link: '/apps/ecommerce/products',
                        parentKey: 'apps-ecommerce',
                    },
                    {
                        key: 'ecommerce-details',
                        label: 'Product Details',
                        link: '/apps/ecommerce/product/details/',
                        parentKey: 'apps-ecommerce',
                    },
                    {
                        key: 'ecommerce-products-edit',
                        label: 'Add Product',
                        link: '/apps/ecommerce/products-edit',
                        parentKey: 'apps-ecommerce',
                    },
                    {
                        key: 'ecommerce-customers',
                        label: 'Customers',
                        link: '/apps/ecommerce/customers',
                        parentKey: 'apps-ecommerce',
                    },
                    {
                        key: 'ecommerce-orders',
                        label: 'Orders',
                        link: '/apps/ecommerce/orders',
                        parentKey: 'apps-ecommerce',
                    },
                    {
                        key: 'ecommerce-order-details',
                        label: 'Order Details',
                        link: '/apps/ecommerce/order/details',
                        parentKey: 'apps-ecommerce',
                    },
                    {
                        key: 'ecommerce-sellers',
                        label: 'Sellers',
                        link: '/apps/ecommerce/sellers',
                        parentKey: 'apps-ecommerce',
                    },
                    {
                        key: 'ecommerce-shopping-cart',
                        label: 'Shopping Cart',
                        link: '/apps/ecommerce/shopping-cart',
                        parentKey: 'apps-ecommerce',
                    },
                    {
                        key: 'ecommerce-checkout',
                        label: 'Checkout',
                        link: '/apps/ecommerce/checkout',
                        parentKey: 'apps-ecommerce',
                    },
                ],
            },
            {
                key: 'apps-crm',
                label: 'CRM',
                isTitle: false,
                icon: 'users',
                parentKey: 'apps',
                collapsed: true,
                children: [
                    {
                        key: 'crm-dashboard',
                        label: 'Dashboard',
                        link: '/apps/crm/dashboard',
                        parentKey: 'apps-crm',
                    },
                    {
                        key: 'crm-contacts',
                        label: 'Contacts',
                        link: '/apps/crm/contacts',
                        parentKey: 'apps-crm',
                    },
                    {
                        key: 'crm-opportunities',
                        label: 'Opportunities',
                        link: '/apps/crm/opportunities',
                        parentKey: 'apps-crm',
                    },
                    {
                        key: 'crm-leads',
                        label: 'Leads',
                        link: '/apps/crm/leads',
                        parentKey: 'apps-crm',
                    },
                    {
                        key: 'crm-customers',
                        label: 'Customers',
                        link: '/apps/crm/customers',
                        parentKey: 'apps-crm',
                    },
                ],
            },
            {
                key: 'apps-email',
                label: 'Email',
                isTitle: false,
                icon: 'mail',
                parentKey: 'apps',
                collapsed: true,
                children: [
                    {
                        key: 'email-inbox',
                        label: 'Inbox',
                        link: '/apps/email/inbox',
                        parentKey: 'apps-email',
                    },
                    {
                        key: 'email-read-email',
                        label: 'Read Email',
                        link: '/apps/email/details',
                        parentKey: 'apps-email',
                    },
                    {
                        key: 'email-compose-email',
                        label: 'Compose Email',
                        link: '/apps/email/compose',
                        parentKey: 'apps-email',
                    },
                ],
            },
            {
                key: 'apps-social',
                label: 'Social Feed',
                isTitle: false,
                icon: 'rss',
                link: '/apps/social-feed',
                badge: { variant: 'pink', text: 'Hot' },
                parentKey: 'apps',
            },
            {
                key: 'apps-companies',
                label: 'Companies',
                isTitle: false,
                icon: 'activity',
                link: '/apps/companies',
                parentKey: 'apps',
            },
            {
                key: 'apps-projects',
                label: 'Projects',
                isTitle: false,
                icon: 'briefcase',
                parentKey: 'apps',
                collapsed: true,
                children: [
                    { key: 'project-list', label: 'List', link: '/apps/projects/list', parentKey: 'apps-projects' },
                    {
                        key: 'project-details',
                        label: 'Details',
                        link: '/apps/projects/details',
                        parentKey: 'apps-projects',
                    },
                    {
                        key: 'project-create-project',
                        label: 'Create Project',
                        link: '/apps/projects/create',
                        parentKey: 'apps-projects',
                    },
                ],
            },
            {
                key: 'apps-tasks',
                label: 'Tasks',
                isTitle: false,
                icon: 'clipboard',
                parentKey: 'apps',
                collapsed: true,
                children: [
                    { key: 'task-list', label: 'List', link: '/apps/tasks/list', parentKey: 'apps-tasks' },
                    { key: 'task-details', label: 'Details', link: '/apps/tasks/details', parentKey: 'apps-tasks' },
                    { key: 'task-kanban', label: 'Kanban Board', link: '/apps/tasks/kanban', parentKey: 'apps-tasks' },
                ],
            },
            {
                key: 'apps-contacts',
                label: 'Contacts',
                isTitle: false,
                icon: 'book',
                parentKey: 'apps',
                collapsed: true,
                children: [
                    {
                        key: 'contacts-list',
                        label: 'Members List',
                        link: '/apps/contacts/list',
                        parentKey: 'apps-contacts',
                    },
                    {
                        key: 'contacts-profile',
                        label: 'Profile',
                        link: '/apps/contacts/profile',
                        parentKey: 'apps-contacts',
                    },
                ],
            },
            {
                key: 'apps-tickets',
                label: 'Tickets',
                isTitle: false,
                icon: 'aperture',
                parentKey: 'apps',
                collapsed: true,
                children: [
                    { key: 'tickets-list', label: 'List', link: '/apps/tickets/list', parentKey: 'apps-tickets' },
                    {
                        key: 'tickets-details',
                        label: 'Details',
                        link: '/apps/tickets/details',
                        parentKey: 'apps-tickets',
                    },
                ],
            },
            {
                key: 'apps-file-manager',
                label: 'File Manager',
                isTitle: false,
                icon: 'folder-plus',
                link: '/apps/file-manager',
                parentKey: 'apps',
            },
        ],
    },
    {
        key: 'extra-pages',
        icon: 'file-text',
        label: 'Pages',
        isTitle: true,
        children: [
            { key: 'page-starter', label: 'Starter', link: '/pages/starter', parentKey: 'extra-pages' },
            { key: 'page-timeline', label: 'Timeline', link: '/pages/timeline', parentKey: 'extra-pages' },
            { key: 'page-sitemap', label: 'Sitemap', link: '/pages/sitemap', parentKey: 'extra-pages' },
            { key: 'page-invoice', label: 'Invoice', link: '/pages/invoice', parentKey: 'extra-pages' },
            { key: 'page-faq', label: 'FAQs', link: '/pages/faq', parentKey: 'extra-pages' },
            {
                key: 'page-search-result',
                label: 'Search Results',
                link: '/pages/serach-results',
                parentKey: 'extra-pages',
            },
            { key: 'page-pricing', label: 'Pricing', link: '/pages/pricing', parentKey: 'extra-pages' },
            {
                key: 'page-maintenance',
                label: 'Maintenance',
                link: '/maintenance',
                target: '_blank',
                parentKey: 'extra-pages',
            },
            {
                key: 'page-upcoming',
                label: 'Coming Soon',
                link: '/upcoming',
                parentKey: 'extra-pages',
            },
            {
                key: 'page-gallery',
                label: 'Gallery',
                link: '/pages/gallery',
                parentKey: 'extra-pages',
            },
            { key: 'page-error-404', label: 'Error - 404', link: '/error-404', parentKey: 'extra-pages' },
            { key: 'page-error-404-two', label: 'Error - 404 Two', link: '/error-404-two', parentKey: 'extra-pages' },
            {
                key: 'page-error-404-alt',
                label: 'Error - 404-alt',
                link: '/pages/error-404-alt',
                parentKey: 'extra-pages',
            },
            { key: 'page-error-500', label: 'Error - 500', link: '/error-500', parentKey: 'extra-pages' },
            { key: 'page-error-500-two', label: 'Error - 500 Two', link: '/error-500-two', parentKey: 'extra-pages' },
        ],
    },
    {
        key: 'base-ui',
        icon: 'briefcase',
        label: 'UI Elements',
        isTitle: true,
        children: [
            { key: 'base-ui-buttons', label: 'Buttons', link: '/ui/buttons', parentKey: 'base-ui' },
            { key: 'base-ui-cards', label: 'Cards', link: '/ui/cards', parentKey: 'base-ui' },
            { key: 'base-ui-avatars', label: 'Avatars', link: '/ui/avatars', parentKey: 'base-ui' },
            { key: 'base-ui-portlets', label: 'Portlets', link: '/ui/portlets', parentKey: 'base-ui' },
            {
                key: 'base-ui-tabs-accordions',
                label: 'Tabs & Accordions',
                link: '/ui/tabs-accordions',
                parentKey: 'base-ui',
            },
            { key: 'base-ui-modals', label: 'Modals', link: '/ui/modals', parentKey: 'base-ui' },
            { key: 'base-ui-placeholders', label: 'Placeholders', link: '/ui/placeholders', parentKey: 'base-ui' },
            { key: 'base-ui-progress', label: 'Progress', link: '/ui/progress', parentKey: 'base-ui' },
            { key: 'base-ui-notifications', label: 'Notifications', link: '/ui/notifications', parentKey: 'base-ui' },
            { key: 'base-ui-spinners', label: 'Spinners', link: '/ui/spinners', parentKey: 'base-ui' },
            { key: 'base-ui-images', label: 'Images', link: '/ui/images', parentKey: 'base-ui' },
            { key: 'base-ui-carousel', label: 'Carousel', link: '/ui/carousel', parentKey: 'base-ui' },
            { key: 'base-ui-listgroups', label: 'List Groups', link: '/ui/listgroups', parentKey: 'base-ui' },
            { key: 'base-ui-embedvideo', label: 'Embed Video', link: '/ui/embedvideo', parentKey: 'base-ui' },
            { key: 'base-ui-dropdown', label: 'Dropdowns', link: '/ui/dropdowns', parentKey: 'base-ui' },
            { key: 'base-ui-ribbons', label: 'Ribbons', link: '/ui/ribbons', parentKey: 'base-ui' },
            {
                key: 'base-ui-tooltips-popovers',
                label: 'Tooltips & Popovers',
                link: '/ui/tooltips-popovers',
                parentKey: 'base-ui',
            },
            { key: 'base-ui-general', label: 'General UI', link: '/ui/general', parentKey: 'base-ui' },
            { key: 'base-ui-typography', label: 'Typography', link: '/ui/typography', parentKey: 'base-ui' },
            { key: 'base-ui-grid', label: 'Grid', link: '/ui/grid', parentKey: 'base-ui' },
        ],
    },
    {
        key: 'components',
        icon: 'package',
        label: 'Components',
        isTitle: true,
        children: [
            {
                key: 'extended-ui',
                label: 'Extended UI',
                isTitle: false,
                icon: 'layers',
                badge: { variant: 'info', text: 'Hot' },
                parentKey: 'components',
                collapsed: true,
                children: [], // Removed all children
            },
            {
                key: 'icons',
                label: 'Icons',
                isTitle: false,
                icon: 'cpu',
                parentKey: 'components',
                collapsed: true,
                children: [], // Removed all children
            },
            {
                key: 'forms',
                label: 'Forms',
                isTitle: false,
                icon: 'bookmark',
                parentKey: 'components',
                collapsed: true,
                children: [], // Removed all children
            },
            {
                key: 'tables',
                label: 'Tables',
                isTitle: false,
                icon: 'grid',
                parentKey: 'components',
                collapsed: true,
                children: [], // Removed all children
            },
            {
                key: 'charts',
                label: 'Charts',
                isTitle: false,
                icon: 'bar-chart-2',
                collapsed: true,
                parentKey: 'components',
                children: [], // Removed all children
            },
            {
                key: 'maps',
                label: 'Maps',
                isTitle: false,
                icon: 'map',
                parentKey: 'components',
                collapsed: true,
                children: [
                    { key: 'maps-googlemaps', label: 'Google Maps', link: '/maps/googlemaps', parentKey: 'maps' },
                    { key: 'maps-vectormaps', label: 'Vector Maps', link: '/maps/vectormaps', parentKey: 'maps' },
                ],
            },
            {
                key: 'menu-levels',
                label: 'Menu Levels',
                isTitle: false,
                icon: 'share-2',
                parentKey: 'components',
                collapsed: true,
                children: [
                    {
                        key: 'menu-levels-1-1',
                        label: 'Level 1.1',
                        link: '/',
                        parentKey: 'menu-levels',
                        collapsed: true,
                        children: [
                            {
                                key: 'menu-levels-2-1',
                                label: 'Level 2.1',
                                link: '/',
                                parentKey: 'menu-levels-1-1',
                                collapsed: true,
                                children: [
                                    {
                                        key: 'menu-levels-3-1',
                                        label: 'Level 3.1',
                                        link: '/',
                                        parentKey: 'menu-levels-2-1',
                                    },
                                    {
                                        key: 'menu-levels-3-2',
                                        label: 'Level 3.2',
                                        link: '/',
                                        parentKey: 'menu-levels-2-1',
                                    },
                                ],
                            },
                            { key: 'menu-levels-2-2', label: 'Level 2.2', link: '/', parentKey: 'menu-levels-1-1' },
                        ],
                    },
                    { key: 'menu-levels-1-2', label: 'Level 1.2', link: '/', parentKey: 'menu-levels' },
                ],
            },
        ],
    },
    { key: 'widgets', label: 'Widgets', isTitle: false, icon: 'gift', link: '/widgets' },
];

// menu items for horizontal layout
const HORIZONTAL_MENU_ITEMS: MenuItem[] = [
    {
        key: 'dashboard',
        icon: 'home',
        label: 'Dashboard',
        isTitle: true,
        link: '/dashboard-1',  // Direct link to Dashboard 1
    },
    {
        key: 'apps',
        icon: 'grid',
        label: 'Apps',
        isTitle: true,
        collapsed: true,
        children: [
            {
                key: 'apps-calendar',
                label: 'Calendar',
                isTitle: false,
                icon: 'calendar',
                link: '/apps/calendar',
                parentKey: 'apps',
            },
            {
                key: 'apps-chat',
                label: 'Chat',
                isTitle: false,
                icon: 'message-square',
                link: '/apps/chat',
                parentKey: 'apps',
            },
            {
                key: 'apps-ecommerce',
                label: 'Ecommerce',
                isTitle: false,
                icon: 'shopping-cart',
                parentKey: 'apps',
                collapsed: true,
                children: [
                    {
                        key: 'ecommerce-dashboard',
                        label: 'Dashboard',
                        link: '/apps/ecommerce/dashboard',
                        parentKey: 'apps-ecommerce',
                    },
                    {
                        key: 'ecommerce-products',
                        label: 'Products',
                        link: '/apps/ecommerce/products',
                        parentKey: 'apps-ecommerce',
                    },
                    {
                        key: 'ecommerce-details',
                        label: 'Product Details',
                        link: '/apps/ecommerce/product/details/',
                        parentKey: 'apps-ecommerce',
                    },
                    {
                        key: 'ecommerce-products-edit',
                        label: 'Add Product',
                        link: '/apps/ecommerce/products-edit',
                        parentKey: 'apps-ecommerce',
                    },
                    {
                        key: 'ecommerce-customers',
                        label: 'Customers',
                        link: '/apps/ecommerce/customers',
                        parentKey: 'apps-ecommerce',
                    },
                    {
                        key: 'ecommerce-orders',
                        label: 'Orders',
                        link: '/apps/ecommerce/orders',
                        parentKey: 'apps-ecommerce',
                    },
                    {
                        key: 'ecommerce-order-details',
                        label: 'Order Details',
                        link: '/apps/ecommerce/order/details',
                        parentKey: 'apps-ecommerce',
                    },
                    {
                        key: 'ecommerce-sellers',
                        label: 'Sellers',
                        link: '/apps/ecommerce/sellers',
                        parentKey: 'apps-ecommerce',
                    },
                    {
                        key: 'ecommerce-shopping-cart',
                        label: 'Shopping Cart',
                        link: '/apps/ecommerce/shopping-cart',
                        parentKey: 'apps-ecommerce',
                    },
                    {
                        key: 'ecommerce-checkout',
                        label: 'Checkout',
                        link: '/apps/ecommerce/checkout',
                        parentKey: 'apps-ecommerce',
                    },
                ],
            },
            {
                key: 'apps-crm',
                label: 'CRM',
                isTitle: false,
                icon: 'users',
                parentKey: 'apps',
                collapsed: true,
                children: [
                    {
                        key: 'crm-dashboard',
                        label: 'Dashboard',
                        link: '/apps/crm/dashboard',
                        parentKey: 'apps-crm',
                    },
                    {
                        key: 'crm-contacts',
                        label: 'Contacts',
                        link: '/apps/crm/contacts',
                        parentKey: 'apps-crm',
                    },
                    {
                        key: 'crm-opportunities',
                        label: 'Opportunities',
                        link: '/apps/crm/opportunities',
                        parentKey: 'apps-crm',
                    },
                    {
                        key: 'crm-leads',
                        label: 'Leads',
                        link: '/apps/crm/leads',
                        parentKey: 'apps-crm',
                    },
                    {
                        key: 'crm-customers',
                        label: 'Customers',
                        link: '/apps/crm/customers',
                        parentKey: 'apps-crm',
                    },
                ],
            },
            {
                key: 'apps-email',
                label: 'Email',
                isTitle: false,
                icon: 'mail',
                parentKey: 'apps',
                collapsed: true,
                children: [
                    {
                        key: 'email-inbox',
                        label: 'Inbox',
                        link: '/apps/email/inbox',
                        parentKey: 'apps-email',
                    },
                    {
                        key: 'email-read-email',
                        label: 'Read Email',
                        link: '/apps/email/details',
                        parentKey: 'apps-email',
                    },
                    {
                        key: 'email-compose-email',
                        label: 'Compose Email',
                        link: '/apps/email/compose',
                        parentKey: 'apps-email',
                    },
                ],
            },
            {
                key: 'apps-social',
                label: 'Social Feed',
                isTitle: false,
                icon: 'rss',
                link: '/apps/social-feed',
                badge: { variant: 'pink', text: 'Hot' },
                parentKey: 'apps',
            },
            {
                key: 'apps-companies',
                label: 'Companies',
                isTitle: false,
                icon: 'activity',
                link: '/apps/companies',
                parentKey: 'apps',
            },
            {
                key: 'apps-projects',
                label: 'Projects',
                isTitle: false,
                icon: 'briefcase',
                parentKey: 'apps',
                collapsed: true,
                children: [
                    { key: 'project-list', label: 'List', link: '/apps/projects/list', parentKey: 'apps-projects' },
                    {
                        key: 'project-details',
                        label: 'Details',
                        link: '/apps/projects/details',
                        parentKey: 'apps-projects',
                    },
                    {
                        key: 'project-create-project',
                        label: 'Create Project',
                        link: '/apps/projects/create',
                        parentKey: 'apps-projects',
                    },
                ],
            },
            {
                key: 'apps-tasks',
                label: 'Tasks',
                isTitle: false,
                icon: 'clipboard',
                parentKey: 'apps',
                collapsed: true,
                children: [
                    { key: 'task-list', label: 'List', link: '/apps/tasks/list', parentKey: 'apps-tasks' },
                    { key: 'task-details', label: 'Details', link: '/apps/tasks/details', parentKey: 'apps-tasks' },
                    { key: 'task-kanban', label: 'Kanban Board', link: '/apps/tasks/kanban', parentKey: 'apps-tasks' },
                ],
            },
            {
                key: 'apps-contacts',
                label: 'Contacts',
                isTitle: false,
                icon: 'book',
                parentKey: 'apps',
                collapsed: true,
                children: [
                    {
                        key: 'contacts-list',
                        label: 'Members List',
                        link: '/apps/contacts/list',
                        parentKey: 'apps-contacts',
                    },
                    {
                        key: 'contacts-profile',
                        label: 'Profile',
                        link: '/apps/contacts/profile',
                        parentKey: 'apps-contacts',
                    },
                ],
            },
            {
                key: 'apps-tickets',
                label: 'Tickets',
                isTitle: false,
                icon: 'aperture',
                parentKey: 'apps',
                collapsed: true,
                children: [
                    { key: 'tickets-list', label: 'List', link: '/apps/tickets/list', parentKey: 'apps-tickets' },
                    {
                        key: 'tickets-details',
                        label: 'Details',
                        link: '/apps/tickets/details',
                        parentKey: 'apps-tickets',
                    },
                ],
            },
            {
                key: 'apps-file-manager',
                label: 'File Manager',
                isTitle: false,
                icon: 'folder-plus',
                link: '/apps/file-manager',
                parentKey: 'apps',
            },
        ],
    },
    {
        key: 'base-ui',
        icon: 'briefcase',
        label: 'UI Elements',
        isTitle: true,
        collapsed: true,
        children: [
            { key: 'base-ui-buttons', label: 'Buttons', link: '/ui/buttons', parentKey: 'base-ui' },
            { key: 'base-ui-cards', label: 'Cards', link: '/ui/cards', parentKey: 'base-ui' },
            { key: 'base-ui-avatars', label: 'Avatars', link: '/ui/avatars', parentKey: 'base-ui' },
            { key: 'base-ui-portlets', label: 'Portlets', link: '/ui/portlets', parentKey: 'base-ui' },
            {
                key: 'base-ui-tabs-accordions',
                label: 'Tabs & Accordions',
                link: '/ui/tabs-accordions',
                parentKey: 'base-ui',
            },
            { key: 'base-ui-modals', label: 'Modals', link: '/ui/modals', parentKey: 'base-ui' },
            { key: 'base-ui-placeholders', label: 'Placeholders', link: '/ui/placeholders', parentKey: 'base-ui' },
            { key: 'base-ui-progress', label: 'Progress', link: '/ui/progress', parentKey: 'base-ui' },
            { key: 'base-ui-notifications', label: 'Notifications', link: '/ui/notifications', parentKey: 'base-ui' },
            { key: 'base-ui-spinners', label: 'Spinners', link: '/ui/spinners', parentKey: 'base-ui' },
            { key: 'base-ui-images', label: 'Images', link: '/ui/images', parentKey: 'base-ui' },
            { key: 'base-ui-carousel', label: 'Carousel', link: '/ui/carousel', parentKey: 'base-ui' },
            { key: 'base-ui-listgroups', label: 'List Groups', link: '/ui/listgroups', parentKey: 'base-ui' },
            { key: 'base-ui-embedvideo', label: 'Embed Video', link: '/ui/embedvideo', parentKey: 'base-ui' },
            { key: 'base-ui-dropdown', label: 'Dropdowns', link: '/ui/dropdowns', parentKey: 'base-ui' },
            { key: 'base-ui-ribbons', label: 'Ribbons', link: '/ui/ribbons', parentKey: 'base-ui' },
            {
                key: 'base-ui-tooltips-popovers',
                label: 'Tooltips & Popovers',
                link: '/ui/tooltips-popovers',
                parentKey: 'base-ui',
            },
            { key: 'base-ui-general', label: 'General UI', link: '/ui/general', parentKey: 'base-ui' },
            { key: 'base-ui-typography', label: 'Typography', link: '/ui/typography', parentKey: 'base-ui' },
            { key: 'base-ui-grid', label: 'Grid', link: '/ui/grid', parentKey: 'base-ui' },
        ],
    },
    {
        key: 'components',
        icon: 'package',
        label: 'Components',
        isTitle: true,
        collapsed: true,
        children: [
            {
                key: 'extended-ui',
                label: 'Extended UI',
                isTitle: false,
                icon: 'layers',
                badge: { variant: 'info', text: 'Hot' },
                parentKey: 'components',
                collapsed: true,
                children: [], // Removed all children
            },
            { key: 'widgets', label: 'Widgets', isTitle: false, icon: 'gift', link: '/widgets', parentKey: 'components', },
            {
                key: 'icons',
                label: 'Icons',
                isTitle: false,
                icon: 'cpu',
                parentKey: 'components',
                collapsed: true,
                children: [], // Removed all children
            },
            {
                key: 'forms',
                label: 'Forms',
                isTitle: false,
                icon: 'bookmark',
                parentKey: 'components',
                collapsed: true,
                children: [], // Removed all children
            },
            {
                key: 'tables',
                label: 'Tables',
                isTitle: false,
                icon: 'grid',
                parentKey: 'components',
                collapsed: true,
                children: [], // Removed all children
            },
            {
                key: 'charts',
                label: 'Charts',
                isTitle: false,
                icon: 'bar-chart-2',
                collapsed: true,
                parentKey: 'components',
                children: [], // Removed all children
            },
            {
                key: 'maps',
                label: 'Maps',
                isTitle: false,
                icon: 'map',
                parentKey: 'components',
                collapsed: true,
                children: [
                    { key: 'maps-googlemaps', label: 'Google Maps', link: '/maps/googlemaps', parentKey: 'maps' },
                    { key: 'maps-vectormaps', label: 'Vector Maps', link: '/maps/vectormaps', parentKey: 'maps' },
                ],
            },
            {
                key: 'menu-levels',
                label: 'Menu Levels',
                isTitle: false,
                icon: 'share-2',
                parentKey: 'components',
                collapsed: true,
                children: [
                    {
                        key: 'menu-levels-1-1',
                        label: 'Level 1.1',
                        link: '/',
                        parentKey: 'menu-levels',
                        collapsed: true,
                        children: [
                            {
                                key: 'menu-levels-2-1',
                                label: 'Level 2.1',
                                link: '/',
                                parentKey: 'menu-levels-1-1',
                                collapsed: true,
                                children: [
                                    {
                                        key: 'menu-levels-3-1',
                                        label: 'Level 3.1',
                                        link: '/',
                                        parentKey: 'menu-levels-2-1',
                                    },
                                    {
                                        key: 'menu-levels-3-2',
                                        label: 'Level 3.2',
                                        link: '/',
                                        parentKey: 'menu-levels-2-1',
                                    },
                                ],
                            },
                            { key: 'menu-levels-2-2', label: 'Level 2.2', link: '/', parentKey: 'menu-levels-1-1' },
                        ],
                    },
                    { key: 'menu-levels-1-2', label: 'Level 1.2', link: '/', parentKey: 'menu-levels' },
                ],
            },
        ],
    },
    {
        key: 'pages',
        icon: 'file-text',
        label: 'Pages',
        isTitle: true,
        collapsed: true,
        children: [
            {
                key: 'error-pages',
                label: 'Errors',
                isTitle: false,
                parentKey: 'pages',
                // collapsed: true,
                children: [
                    { key: 'page-error-404', label: 'Error - 404', link: '/error-404', parentKey: 'error-pages' },
                    { key: 'page-error-404-two', label: 'Error - 404 Two', link: '/error-404-two', parentKey: 'error-pages' },
                    {
                        key: 'page-error-404-alt',
                        label: 'Error - 404-alt',
                        link: '/pages/error-404-alt',
                        parentKey: 'error-pages',
                    },
                    { key: 'page-error-500', label: 'Error - 500', link: '/error-500', parentKey: 'error-pages' },
                    { key: 'page-error-500-two', label: 'Error - 500 Two', link: '/error-500-two', parentKey: 'error-pages' },
                ]
            },
            {
                key: 'extra-pages',
                label: 'Utility',
                isTitle: false,
                parentKey: 'pages',
                // collapsed: true,
                children: [
                    { key: 'page-starter', label: 'Starter', link: '/pages/starter', parentKey: 'extra-pages' },
                    { key: 'page-timeline', label: 'Timeline', link: '/pages/timeline', parentKey: 'extra-pages' },
                    { key: 'page-sitemap', label: 'Sitemap', link: '/pages/sitemap', parentKey: 'extra-pages' },
                    { key: 'page-invoice', label: 'Invoice', link: '/pages/invoice', parentKey: 'extra-pages' },
                    { key: 'page-faq', label: 'FAQs', link: '/pages/faq', parentKey: 'extra-pages' },
                    {
                        key: 'page-search-result',
                        label: 'Search Results',
                        link: '/pages/serach-results',
                        parentKey: 'extra-pages',
                    },
                    { key: 'page-pricing', label: 'Pricing', link: '/pages/pricing', parentKey: 'extra-pages' },
                    {
                        key: 'page-maintenance',
                        label: 'Maintenance',
                        link: '/maintenance',
                        target: '_blank',
                        parentKey: 'extra-pages',
                    },
                    {
                        key: 'page-upcoming',
                        label: 'Coming Soon',
                        link: '/upcoming',
                        parentKey: 'extra-pages',
                    },
                    {
                        key: 'page-gallery',
                        label: 'Gallery',
                        link: '/pages/gallery',
                        parentKey: 'extra-pages',
                    },
                ]
            }

        ]
    }

];

export { MENU_ITEMS, TWO_COl_MENU_ITEMS, HORIZONTAL_MENU_ITEMS };