import { TicketItem } from "./tickets.model";

const TICKETSLIST: TicketItem[] = [
    {
        id: '#1256',
        requested_by: {
            name: 'George A. Llanes',
            image: 'assets/images/users/user-1.jpg',
        },
        subject: 'Support for theme',
        assignee: 'assets/images/users/user-10.jpg',
        priority: 'Low',
        status: 'Open',
        created_date: '2017-04-28',
        due_date: '2017-04-28',
    },
    {
        id: '#2542',
        requested_by: {
            name: 'Jose D. Delacruz',
            image: 'assets/images/users/user-9.jpg',
        },
        subject: 'New submission on your website',
        assignee: 'assets/images/users/user-2.jpg',
        priority: 'Medium',
        status: 'Closed',
        created_date: '2008-04-25',
        due_date: '2008-04-25',
    },
    {
        id: '#320',
        requested_by: {
            name: 'Phyllis K. Maciel',
            image: 'assets/images/users/user-3.jpg',
        },
        subject: 'Verify your new email address!',
        assignee: 'assets/images/users/user-8.jpg',
        priority: 'High',
        status: 'Open',
        created_date: '2017-04-20',
        due_date: '2017-04-25',
    },
    {
        id: '#1254',
        requested_by: {
            name: 'Margeret V. Ligon',
            image: 'assets/images/users/user-8.jpg',
        },
        subject: 'Your application has been received!',
        assignee: 'assets/images/users/user-3.jpg',
        priority: 'High',
        status: 'Closed',
        created_date: '2017-01-04',
        due_date: '21/05/2017',
    },
    {
        id: '#1020',
        requested_by: {
            name: 'Erwin E. Brown',
            image: 'assets/images/users/user-2.jpg',
        },
        subject: 'A new rating has been received',
        assignee: 'assets/images/users/user-9.jpg',
        priority: 'Medium',
        status: 'Closed',
        created_date: '2013-08-11',
        due_date: '2013-08-30',
    },
    {
        id: '#854',
        requested_by: {
            name: 'William L. Trent',
            image: 'assets/images/users/user-10.jpg',
        },
        subject: 'Your Profile has been accepted',
        assignee: 'assets/images/users/user-1.jpg',
        priority: 'High',
        status: 'Open',
        created_date: '2017-01-04',
        due_date: '21/05/2017',
    },
    {
        id: '#9501',
        requested_by: {
            name: 'Amy R. Barnaby',
            image: 'assets/images/users/user-1.jpg',
        },
        subject: 'Homeworth for your property increased',
        assignee: 'assets/images/users/user-10.jpg',
        priority: 'Low',
        status: 'Open',
        created_date: '2017-01-04',
        due_date: '21/05/2017',
    },
    {
        id: '#3652',
        requested_by: {
            name: 'Jessica T. Phillips',
            image: 'assets/images/users/user-9.jpg',
        },
        subject: 'Item Support Message sent',
        assignee: 'assets/images/users/user-2.jpg',
        priority: 'Medium',
        status: 'Closed',
        created_date: '2017-01-04',
        due_date: '21/05/2017',
    },
    {
        id: '#9852',
        requested_by: {
            name: 'Debra J. Wilson',
            image: 'assets/images/users/user-3.jpg',
        },
        subject: 'Your item has been updated!',
        assignee: 'assets/images/users/user-8.jpg',
        priority: 'High',
        status: 'Open',
        created_date: '2017-01-04',
        due_date: '21/05/2017',
    },
    {
        id: '#3652',
        requested_by: {
            name: 'Luke J. Sain',
            image: 'assets/images/users/user-8.jpg',
        },
        subject: 'Your password has been reset',
        assignee: 'assets/images/users/user-3.jpg',
        priority: 'Low',
        status: 'Open',
        created_date: '2017-01-04',
        due_date: '21/05/2017',
    },
    {
        id: '#1352',
        requested_by: {
            name: 'Karen R. Doyle',
            image: 'assets/images/users/user-2.jpg',
        },
        subject: 'Question regarding your Bootstrap Theme',
        assignee: 'assets/images/users/user-9.jpg',
        priority: 'High',
        status: 'Open',
        created_date: '2017-01-04',
        due_date: '21/05/2017',
    },
    {
        id: '#3562',
        requested_by: {
            name: 'Freddie J. Plourde',
            image: 'assets/images/users/user-10.jpg',
        },
        subject: 'Security alert for my account',
        assignee: 'assets/images/users/user-1.jpg',
        priority: 'Low',
        status: 'Open',
        created_date: '2017-01-04',
        due_date: '21/05/2017',
    },
    {
        id: '#3658',
        requested_by: {
            name: 'Darrell J. Cook',
            image: 'assets/images/users/user-1.jpg',
        },
        subject: 'Christopher S. Ahmad',
        assignee: 'assets/images/users/user-10.jpg',
        priority: 'Medium',
        status: 'Closed',
        created_date: '2017-01-04',
        due_date: '21/05/2017',
    },
    {
        id: '#2251',
        requested_by: {
            name: 'Mark C. Diaz',
            image: 'assets/images/users/user-9.jpg',
        },
        subject: 'Verify your new email address!',
        assignee: 'assets/images/users/user-2.jpg',
        priority: 'High',
        status: 'Open',
        created_date: '2017-01-04',
        due_date: '21/05/2017',
    },
    {
        id: '#3654',
        requested_by: {
            name: 'Robert K. Joseph',
            image: 'assets/images/users/user-3.jpg',
        },
        subject: 'Support for theme',
        assignee: 'assets/images/users/user-8.jpg',
        priority: 'Low',
        status: 'Open',
        created_date: '2017-01-04',
        due_date: '21/05/2017',
    },
];

export { TICKETSLIST };