import { CompanyInfoItem, CRMCustomer, LeadItem, PerformanceData } from "./crm.model";

//customer data
const CRMCUSTOMERS: CRMCustomer[] = [
    {
        id: 1,
        name: 'Abagael Breslau',
        phone: '(461) 3636077',
        email: 'abreslau0@wiley.com',
        location: 'China',
        created_date: '7/4/2019',
        status: 'Active',
        company: 'Vine Corporation',
        avatar: 'assets/images/users/user-1.jpg'
    },
    {
        id: 2,
        name: 'Veradis Taber',
        phone: '(917) 2590629',
        email: 'vtaber1@ucoz.com',
        location: 'Venezuela',
        created_date: '7/8/2019',
        status: 'Active',
        company: 'Blue Motors',
        avatar: 'assets/images/users/user-2.jpg'
    },
    {
        id: 3,
        name: 'Lindon Ceeley',
        phone: '(925) 9515307',
        email: 'lceeley2@fotki.com',
        location: 'Panama',
        created_date: '7/20/2019',
        status: 'Active',
        company: 'Arcanetworks',
        avatar: 'assets/images/users/user-3.jpg'
    },
    {
        id: 4,
        name: 'Mendel Alfonzo',
        phone: '(295) 3668262',
        email: 'malfonzo3@irs.gov',
        location: 'France',
        created_date: '7/22/2019',
        status: 'Active',
        company: 'Boar Records',
        avatar: 'assets/images/users/user-4.jpg'
    },
    {
        id: 5,
        name: 'Dorrie Tindley',
        phone: '(809) 2120936',
        email: 'dtindley4@so-net.ne.jp',
        location: 'Colombia',
        created_date: '7/14/2019',
        status: 'Blocked',
        company: 'Bearings',
        avatar: 'assets/images/users/user-2.jpg'
    },
    {
        id: 6,
        name: 'Kata MacKnight',
        phone: '(402) 3164595',
        email: 'kmacknight5@boston.com',
        location: 'China',
        created_date: '7/10/2019',
        status: 'Active',
        company: 'Shadowshine',
        avatar: 'assets/images/users/user-6.jpg'
    },
    {
        id: 7,
        name: 'Mateo Kingzeth',
        phone: '(941) 2564726',
        email: 'mkingzeth6@google.com.hk',
        location: 'China',
        created_date: '7/18/2019',
        status: 'Active',
        company: 'Crowares',
        avatar: 'assets/images/users/user-8.jpg'
    },
    {
        id: 8,
        name: 'Jayson Creaney',
        phone: '(969) 3198297',
        email: 'jcreaney7@netvibes.com',
        location: 'Malaysia',
        created_date: '7/19/2019',
        status: 'Blocked',
        company: 'Vine Corporation',
        avatar: 'assets/images/users/user-10.jpg'
    },
    {
        id: 9,
        name: 'Elita Ortmann',
        phone: '(283) 1302865',
        email: 'eortmann8@pinterest.com',
        location: 'South Korea',
        created_date: '7/2/2019',
        status: 'Blocked',
        company: 'Orangations',
        avatar: 'assets/images/users/user-1.jpg'
    },
    {
        id: 10,
        name: 'Tyne Hollidge',
        phone: '(529) 2241787',
        email: 'thollidge9@ebay.co.uk',
        location: 'China',
        created_date: '7/11/2019',
        status: 'Active',
        company: 'Apexlife',
        avatar: 'assets/images/users/user-2.jpg'
    },
    {
        id: 11,
        name: 'Ezmeralda Piggrem',
        phone: '(532) 2561412',
        email: 'epiggrema@addtoany.com',
        location: 'Cambodia',
        created_date: '7/6/2019',
        status: 'Blocked',
        company: 'Apexlife',
        avatar: 'assets/images/users/user-3.jpg'
    },
    {
        id: 12,
        name: 'Kalina Dabels',
        phone: '(953) 8150340',
        email: 'kdabelsb@typepad.com',
        location: 'Mexico',
        created_date: '7/16/2019',
        status: 'Active',
        company: 'Vine Corporation',
        avatar: 'assets/images/users/user-4.jpg'
    },
    {
        id: 13,
        name: 'Claudianus Gommes',
        phone: '(791) 6099303',
        email: 'cgommesc@berkeley.edu',
        location: 'Indonesia',
        created_date: '7/14/2019',
        status: 'Active',
        company: 'Apexlife',
        avatar: 'assets/images/users/user-5.jpg'
    },
    {
        id: 14,
        name: 'Ulrikaumeko Jentle',
        phone: '(478) 8204063',
        email: 'ujentled@pagesperso-orange.fr',
        location: 'Sweden',
        created_date: '7/25/2019',
        status: 'Active',
        company: 'Vine Corporation',
        avatar: 'assets/images/users/user-6.jpg'
    },
    {
        id: 15,
        name: 'Peria Richens',
        phone: '(423) 7419337',
        email: 'prichense@google.it',
        location: 'Indonesia',
        created_date: '7/20/2019',
        status: 'Blocked',
        company: 'Vine Corporation',
        avatar: 'assets/images/users/user-7.jpg'
    },
    {
        id: 16,
        name: 'Sollie Ramelet',
        phone: '(600) 7539738',
        email: 'srameletf@hubpages.com',
        location: 'Brazil',
        created_date: '7/3/2019',
        status: 'Blocked',
        company: 'Vine Corporation',
        avatar: 'assets/images/users/user-8.jpg'
    },
    {
        id: 17,
        name: 'Hodge Diviney',
        phone: '(311) 8358001',
        email: 'hdivineyg@ycombinator.com',
        location: 'Belarus',
        created_date: '7/28/2019',
        status: 'Blocked',
        company: 'Vine Corporation',
        avatar: 'assets/images/users/user-9.jpg'
    },
    {
        id: 18,
        name: 'Roger Lidster',
        phone: '(146) 1370107',
        email: 'rlidsterh@redcross.org',
        location: 'Indonesia',
        created_date: '7/5/2019',
        status: 'Blocked',
        company: 'Vine Corporation',
        avatar: 'assets/images/users/user-10.jpg'
    },
    {
        id: 19,
        name: 'Caprice Custed',
        phone: '(239) 8054555',
        email: 'ccustedi@godaddy.com',
        location: 'Russia',
        created_date: '7/14/2019',
        status: 'Active',
        company: 'Vine Corporation',
        avatar: 'assets/images/users/user-1.jpg'
    },
    {
        id: 20,
        name: 'Becki Filer',
        phone: '(128) 9346017',
        email: 'bfilerj@xrea.com',
        location: 'Madagascar',
        created_date: '7/11/2019',
        status: 'Blocked',
        company: 'Vine Corporation',
        avatar: 'assets/images/users/user-2.jpg'
    },
    {
        id: 21,
        name: 'Rube Sjostrom',
        phone: '(216) 7061924',
        email: 'rsjostromk@blogger.com',
        location: 'France',
        created_date: '7/28/2019',
        status: 'Blocked',
        company: 'Vine Corporation',
        avatar: 'assets/images/users/user-3.jpg'
    },
    {
        id: 22,
        name: 'Gris Biggin',
        phone: '(269) 4756082',
        email: 'gbigginl@usa.gov',
        location: 'Indonesia',
        created_date: '7/27/2019',
        status: 'Active',
        company: 'Vine Corporation',
        avatar: 'assets/images/users/user-4.jpg'
    },
    {
        id: 23,
        name: 'Les Blain',
        phone: '(138) 1015423',
        email: 'lblainm@wsj.com',
        location: 'China',
        created_date: '7/21/2019',
        status: 'Active',
        company: 'Vine Corporation',
        avatar: 'assets/images/users/user-5.jpg'
    },
    {
        id: 24,
        name: 'Adelaida MacWhan',
        phone: '(396) 7710932',
        email: 'amacwhann@abc.net.au',
        location: 'Nigeria',
        created_date: '7/27/2019',
        status: 'Blocked',
        company: 'Vine Corporation',
        avatar: 'assets/images/users/user-6.jpg'
    },
    {
        id: 25,
        name: 'Marco Capon',
        phone: '(315) 8620366',
        email: 'mcapono@ucla.edu',
        location: 'China',
        created_date: '7/1/2019',
        status: 'Active',
        company: 'Vine Corporation',
        avatar: 'assets/images/users/user-7.jpg'
    },
    {
        id: 26,
        name: 'Cordula Goude',
        phone: '(244) 8639717',
        email: 'cgoudep@indiatimes.com',
        location: 'China',
        created_date: '7/4/2019',
        status: 'Active',
        company: 'Vine Corporation',
        avatar: 'assets/images/users/user-8.jpg'
    },
    {
        id: 27,
        name: 'Pippa Piken',
        phone: '(440) 3470724',
        email: 'ppikenq@vistaprint.com',
        location: 'Peru',
        created_date: '7/23/2019',
        status: 'Blocked',
        company: 'Vine Corporation',
        avatar: 'assets/images/users/user-9.jpg'
    },
    {
        id: 28,
        name: 'Katharina Snell',
        phone: '(252) 7933179',
        email: 'ksnellr@spiegel.de',
        location: 'Sierra Leone',
        created_date: '7/7/2019',
        status: 'Blocked',
        company: 'Vine Corporation',
        avatar: 'assets/images/users/user-10.jpg'
    },
    {
        id: 29,
        name: 'Friedrich Brickner',
        phone: '(909) 3774612',
        email: 'fbrickners@nba.com',
        location: 'Taiwan',
        created_date: '7/19/2019',
        status: 'Active',
        company: 'Vine Corporation',
        avatar: 'assets/images/users/user-11.jpg'
    },
    {
        id: 30,
        name: 'Kilian Auden',
        phone: '(100) 2329345',
        email: 'kaudent@amazon.de',
        location: 'Russia',
        created_date: '7/9/2019',
        status: 'Active',
        company: 'Vine Corporation',
        avatar: 'assets/images/users/user-1.jpg'
    },
    {
        id: 31,
        name: 'Genevieve Rouff',
        phone: '(430) 9011662',
        email: 'grouffu@independent.co.uk',
        location: 'United Kingdom',
        created_date: '7/6/2019',
        status: 'Blocked',
        company: 'Vine Corporation',
        avatar: 'assets/images/users/user-2.jpg'
    },
    {
        id: 32,
        name: 'Hobard Stiles',
        phone: '(998) 7877955',
        email: 'hstilesv@bbc.co.uk',
        location: 'China',
        created_date: '7/3/2019',
        status: 'Active',
        company: 'Vine Corporation',
        avatar: 'assets/images/users/user-3.jpg'
    },
    {
        id: 33,
        name: 'Leoline Papps',
        phone: '(876) 9399111',
        email: 'lpappsw@xrea.com',
        location: 'Indonesia',
        created_date: '7/15/2019',
        status: 'Blocked',
        company: 'Vine Corporation',
        avatar: 'assets/images/users/user-6.jpg'
    },
    {
        id: 34,
        name: 'Deloria Storre',
        phone: '(636) 5767463',
        email: 'dstorrex@hp.com',
        location: 'Ukraine',
        created_date: '7/13/2019',
        status: 'Active',
        company: 'Vine Corporation',
        avatar: 'assets/images/users/user-4.jpg'
    },
    {
        id: 35,
        name: 'Mickie Bolitho',
        phone: '(301) 1571490',
        email: 'mbolithoy@gizmodo.com',
        location: 'Vietnam',
        created_date: '7/24/2019',
        status: 'Blocked',
        company: 'Vine Corporation',
        avatar: 'assets/images/users/user-7.jpg'
    },
    {
        id: 36,
        name: 'Hope Hartil',
        phone: '(318) 4606738',
        email: 'hhartilz@gnu.org',
        location: 'China',
        created_date: '7/27/2019',
        status: 'Active',
        company: 'Vine Corporation',
        avatar: 'assets/images/users/user-5.jpg'
    },
    {
        id: 37,
        name: 'Tadio Simmons',
        phone: '(914) 4763589',
        email: 'tsimmons10@chronoengine.com',
        location: 'Costa Rica',
        created_date: '7/21/2019',
        status: 'Active',
        company: 'Vine Corporation',
        avatar: 'assets/images/users/user-8.jpg'
    },
    {
        id: 38,
        name: 'Arda Bickers',
        phone: '(176) 2017597',
        email: 'abickers11@tmall.com',
        location: 'Malawi',
        created_date: '7/28/2019',
        status: 'Blocked',
        company: 'Vine Corporation',
        avatar: 'assets/images/users/user-9.jpg'
    },
    {
        id: 39,
        name: 'Drucill Thurman',
        phone: '(478) 6223976',
        email: 'dthurman12@skype.com',
        location: 'Brazil',
        created_date: '7/5/2019',
        status: 'Blocked',
        company: 'Vine Corporation',
        avatar: 'assets/images/users/user-11.jpg'
    },
    {
        id: 40,
        name: 'Cullin Endle',
        phone: '(960) 4792971',
        email: 'cendle13@wp.com',
        location: 'Philippines',
        created_date: '7/13/2019',
        status: 'Blocked',
        company: 'Vine Corporation',
        avatar: 'assets/images/users/user-10.jpg'
    },
    {
        id: 41,
        name: 'Yves Swin',
        phone: '(468) 9264240',
        email: 'yswin14@mysql.com',
        location: 'Venezuela',
        created_date: '7/20/2019',
        status: 'Active',
        company: 'Vine Corporation',
        avatar: 'assets/images/users/user-8.jpg'
    },
    {
        id: 42,
        name: 'Colleen Ilieve',
        phone: '(491) 2014072',
        email: 'cilieve15@usatoday.com',
        location: 'Japan',
        created_date: '7/15/2019',
        status: 'Active',
        company: 'Vine Corporation',
        avatar: 'assets/images/users/user-6.jpg'
    },
    {
        id: 43,
        name: 'Mable Squires',
        phone: '(781) 2650707',
        email: 'msquires16@cafepress.com',
        location: 'Pakistan',
        created_date: '7/4/2019',
        status: 'Blocked',
        company: 'Vine Corporation',
        avatar: 'assets/images/users/user-4.jpg'
    },
    {
        id: 44,
        name: 'Francklyn Oughtright',
        phone: '(123) 5880543',
        email: 'foughtright17@timesonline.co.uk',
        location: 'China',
        created_date: '7/1/2019',
        status: 'Blocked',
        company: 'Vine Corporation',
        avatar: 'assets/images/users/user-2.jpg'
    },
    {
        id: 45,
        name: 'Holly Mabley',
        phone: '(390) 8411669',
        email: 'hmabley18@smugmug.com',
        location: 'Spain',
        created_date: '7/21/2019',
        status: 'Blocked',
        company: 'Vine Corporation',
        avatar: 'assets/images/users/user-11.jpg'
    },
    {
        id: 46,
        name: 'Elvin Haistwell',
        phone: '(627) 2488531',
        email: 'ehaistwell19@ebay.com',
        location: 'Indonesia',
        created_date: '7/28/2019',
        status: 'Blocked',
        company: 'Vine Corporation',
        avatar: 'assets/images/users/user-9.jpg'
    },
    {
        id: 47,
        name: 'Donaugh Simms',
        phone: '(971) 9299447',
        email: 'dsimms1a@nytimes.com',
        location: 'China',
        created_date: '7/4/2019',
        status: 'Active',
        company: 'Vine Corporation',
        avatar: 'assets/images/users/user-7.jpg'
    },
    {
        id: 48,
        name: "Ogdan A'Barrow",
        phone: '(232) 9095847',
        email: 'oabarrow1b@princeton.edu',
        location: 'Philippines',
        created_date: '7/10/2019',
        status: 'Blocked',
        company: 'Vine Corporation',
        avatar: 'assets/images/users/user-5.jpg'
    },
    {
        id: 49,
        name: 'Lydie Sykes',
        phone: '(430) 2945766',
        email: 'lsykes1c@123-reg.co.uk',
        location: 'Bangladesh',
        created_date: '7/26/2019',
        status: 'Active',
        company: 'Vine Corporation',
        avatar: 'assets/images/users/user-3.jpg'
    },
    {
        id: 50,
        name: 'Justen Itscovitz',
        phone: '(182) 1712572',
        email: 'jitscovitz1d@cbslocal.com',
        location: 'Canada',
        created_date: '7/3/2019',
        status: 'Blocked',
        company: 'Vine Corporation',
        avatar: 'assets/images/users/user-1.jpg'
    }
];

// company data
const COMPANYLIST: CompanyInfoItem[] = [
    {
        id: 1,
        logo: 'assets/images/companies/amazon.png',
        name: 'Amazon Inc.',
        location: 'Seattle, Washington',
        category: 'Ecommerce',
        email: 'collier@jourrapide.com',
        phone: '828-216-2190',
        date: 'October 22, 2018',
        status: 'Hot',
    },
    {
        id: 2,
        logo: 'assets/images/companies/apple.png',
        name: 'Apple Inc.',
        location: 'Cupertino, California',
        category: 'Ecommerce',
        email: 'deanes@dayrep.com',
        phone: '077 6157 4248',
        date: 'September 08, 2018',
        status: 'Cold',
    },
    {
        id: 3,
        logo: 'assets/images/companies/google.png',
        name: 'Google LLC',
        location: 'Menlo Park, California',
        category: 'Search engine',
        email: 'nnac@hotmai.us',
        phone: '(216) 76 298 896',
        date: 'October 10, 2018',
        status: 'In-progress',
    },
    {
        id: 4,
        logo: 'assets/images/companies/airbnb.png',
        name: 'Airbnb Inc.',
        location: 'San Francisco, California',
        category: 'Real Estate',
        email: 'austin@dayrep.com',
        phone: '(02) 75 150 655',
        date: 'August 18, 2018',
        status: 'Lost',
    },
    {
        id: 5,
        logo: 'assets/images/companies/cisco.png',
        name: 'Cisco Systems',
        location: 'San Jose, California',
        category: 'Operating Systems',
        email: 'annette@email.net',
        phone: '(+15) 73 483 758',
        date: 'March 28, 2018',
        status: 'Won',
    },
];

// performance data
const TOPPERFORMING: PerformanceData[] = [
    {
        id: 1,
        user: 'Jeremy Young',
        position: 'Senior Sales Executive',
        leads: 187,
        deals: 154,
        tasks: 49,
    },
    {
        id: 2,
        user: 'Thomas Krueger',
        position: 'Senior Sales Executive',
        leads: 235,
        deals: 127,
        tasks: 83,
    },
    {
        id: 3,
        user: 'Pete Burdine',
        position: 'Senior Sales Executive',
        leads: 365,
        deals: 148,
        tasks: 62,
    },
    {
        id: 4,
        user: 'Mary Nelson',
        position: 'Senior Sales Executive',
        leads: 753,
        deals: 159,
        tasks: 258,
    },
    {
        id: 5,
        user: 'Kevin Grove',
        position: 'Senior Sales Executive',
        leads: 458,
        deals: 126,
        tasks: 73,
    }
];

// recent leads
const RECENTLEADS: LeadItem[] = [
    {
        id: 1,
        name: 'Risa Pearson',
        avatar: 'assets/images/users/user-5.jpg',
        email: 'richard.john@mail.com',
        status: 'Cold',
    },
    {
        id: 2,
        name: 'Margaret D. Evans',
        avatar: 'assets/images/users/user-2.jpg',
        email: 'margaret.evans@rhyta.com',
        status: 'Lost',
    },
    {
        id: 3,
        name: 'Bryan J. Luellen',
        avatar: 'assets/images/users/user-3.jpg',
        email: 'bryuellen@dayrep.com',
        status: 'Won',
    },
    {
        id: 4,
        name: 'Kathryn S. Collier',
        avatar: 'assets/images/users/user-4.jpg',
        email: 'collier@jourrapide.com',
        status: 'Cold',
    },
    {
        id: 5,
        name: 'Timothy Kauper',
        avatar: 'assets/images/users/user-1.jpg',
        email: 'thykauper@rhyta.com',
        status: 'Cold',
    },
    {
        id: 6,
        name: 'Zara Raws',
        avatar: 'assets/images/users/user-6.jpg',
        email: 'austin@dayrep.com',
        status: 'Won',
    },
];

export { CRMCUSTOMERS, COMPANYLIST, TOPPERFORMING, RECENTLEADS }